"""Commerce/payment subsystem for DeepTutor Enterprise.

Implemented as a self-contained file-store over ``data/system`` (the same
deployment-state root the multi-user layer uses for grants, auth and audit),
so a private deployment has exactly one tree to mount and back up.  Vended
routers live in :mod:`deeptutor.api.routers.payment`.
"""

from __future__ import annotations

from .admin import (
    GATEWAY_CDK,
    GATEWAY_NAMES,
    GATEWAY_SECRET_MASK,
    PLAN_ID_RE,
    VALID_PERIODS,
    PlanValidationError,
    admin_get_order,
    admin_list_orders,
    admin_order_view,
    admin_refund_order,
    delete_plan,
    load_gateway_config,
    normalize_plan,
    public_gateways,
    redact_gateways,
    restore_gateway_secrets,
    save_gateways,
    save_plans,
    upsert_plan,
    validate_gateways,
)
from .cdk import (
    CODE_STATUS_EXPIRED,
    CODE_STATUS_REDEEMED,
    CODE_STATUS_UNUSED,
    REDEEM_ATTEMPTS_PER_HOUR,
    REDEEM_WINDOW_SECONDS,
    CDKNotFoundError,
    CDKValidationError,
    RedeemFailure,
    cdk_batch_path,
    cdk_store_path,
    describe_code_digest,
    export_batch_codes,
    generate_batch,
    list_batches,
    list_codes_for_batch,
    lookup_batch,
    redeem_cdk,
)
from .gateways import (
    GATEWAY_EPAY,
    GATEWAY_WECHAT,
    GatewayError,
    SignatureVerificationError,
    active_gateway,
    list_active_gateways,
    load_gateways,
)
from .orders import (
    DEFAULT_ORDER_EXPIRE_MINUTES,
    ORDER_STATUS_COMPLETED,
    ORDER_STATUS_EXPIRED,
    ORDER_STATUS_FAILED,
    ORDER_STATUS_GRANTED,
    ORDER_STATUS_PAID,
    ORDER_STATUS_PENDING,
    ORDER_STATUS_REFUNDED,
    OrderError,
    OrderNotFoundError,
    create_order,
    expire_stale_orders,
    fulfill_order,
    get_order,
    get_order_by_trade_no,
    list_orders,
    order_status_view,
    transition_order,
)
from .provisioning import bind_plan_books, grant_for_plan, merge_grant, provision_plan
from .service import (
    PaymentServiceError,
    PlanNotFoundError,
    create_payment_order,
    find_plan,
    load_plans,
    plans_path,
    public_plan,
    public_plans,
)

__all__ = [
    "CDKNotFoundError",
    "GATEWAY_CDK",
    "GATEWAY_NAMES",
    "GATEWAY_SECRET_MASK",
    "PLAN_ID_RE",
    "PlanValidationError",
    "VALID_PERIODS",
    "admin_get_order",
    "admin_list_orders",
    "admin_order_view",
    "admin_refund_order",
    "delete_plan",
    "load_gateway_config",
    "normalize_plan",
    "public_gateways",
    "redact_gateways",
    "restore_gateway_secrets",
    "save_gateways",
    "save_plans",
    "upsert_plan",
    "validate_gateways",
    "CDKValidationError",
    "CODE_STATUS_EXPIRED",
    "CODE_STATUS_REDEEMED",
    "CODE_STATUS_UNUSED",
    "DEFAULT_ORDER_EXPIRE_MINUTES",
    "GATEWAY_EPAY",
    "GATEWAY_WECHAT",
    "GatewayError",
    "ORDER_STATUS_COMPLETED",
    "ORDER_STATUS_EXPIRED",
    "ORDER_STATUS_FAILED",
    "ORDER_STATUS_GRANTED",
    "ORDER_STATUS_PAID",
    "ORDER_STATUS_PENDING",
    "ORDER_STATUS_REFUNDED",
    "OrderError",
    "OrderNotFoundError",
    "PaymentServiceError",
    "PlanNotFoundError",
    "REDEEM_ATTEMPTS_PER_HOUR",
    "REDEEM_WINDOW_SECONDS",
    "RedeemFailure",
    "SignatureVerificationError",
    "active_gateway",
    "bind_plan_books",
    "cdk_batch_path",
    "cdk_store_path",
    "create_order",
    "create_payment_order",
    "describe_code_digest",
    "expire_stale_orders",
    "export_batch_codes",
    "find_plan",
    "fulfill_order",
    "generate_batch",
    "get_order",
    "get_order_by_trade_no",
    "grant_for_plan",
    "list_active_gateways",
    "list_batches",
    "list_codes_for_batch",
    "list_orders",
    "load_gateways",
    "load_plans",
    "lookup_batch",
    "merge_grant",
    "order_status_view",
    "plans_path",
    "provision_plan",
    "public_plan",
    "public_plans",
    "redeem_cdk",
    "transition_order",
]
