"""SSO providers: OIDC authorization-code + SAML HTTP-POST assertion verify.

Both flows converge on the same outcome — a verified
:class:`SsoProfile` that the caller turns into a local session by creating or
reusing an account (see :func:`upsert_sso_user`).

Security invariants (the hard requirements from the issue):

- **OIDC**: the id token signature is verified against the provider's JWKS,
  the ``iss`` claim must match the configured issuer exactly, and the
  authorization-code exchange happens server-side (never a response_type=token
  implicit flow).  The ``state`` value returned in the callback must match the
  one we generated and stored in the user's session cookie.
- **SAML**: the Assertion's XML signature is verified against the IdP's
  signing certificate (parsed with ``defusedxml`` so no billion-laughs/entity
  expansion can run), the Assertion must name our audience, and the
  ``<saml:Issuer>`` must match the configured IdP entity id.

Both protocols never log id token secrets / SAML assertion bodies.
"""

from __future__ import annotations

import hashlib
import hmac
import logging
import secrets
from typing import Any
from urllib.parse import urlencode

import httpx

from .contracts import (
    OidcProviderConfig,
    SamlProviderConfig,
    SamlResponseEnvelope,
    SsoProfile,
    SsoStateError,
    SsoVerificationError,
)

logger = logging.getLogger(__name__)

_STATE_COOKIE = "sso_state"
_STATE_MAX_AGE = 600  # 10 minutes

_SCOPE_DELIMITER = " "


# ---------------------------------------------------------------------------
# OIDC — authorization-code flow
# ---------------------------------------------------------------------------


def build_oidc_authorization_url(
    provider: OidcProviderConfig,
    state: str,
    *,
    nonce: str = "",
) -> str:
    """Build the IdP authorization URL for the code flow.

    ``state`` must be generated by the caller and stored server-side (it is
    compared on callback; the flow never trusts the browser to carry the
    truth).
    """
    params = {
        "response_type": "code",
        "client_id": provider.client_id,
        "redirect_uri": provider.redirect_uri or "/api/auth/sso/oidc/callback",
        "scope": _SCOPE_DELIMITER.join(provider.scopes),
        "state": state,
    }
    if nonce:
        params["nonce"] = nonce
    return f"{provider.authorization_endpoint}?{urlencode(params)}"


async def exchange_oidc_code(
    provider: OidcProviderConfig,
    code: str,
    redirect_uri: str,
    state: str,
    expected_state: str,
    *,
    http_client: httpx.AsyncClient | None = None,
) -> SsoProfile:
    """Exchange an authorization code for an id token and verify it.

    Steps:
    1. ``state`` guard — constant-time compare.
    2. Server-side token exchange (never from the browser).
    3. Fetch JWKS from ``provider.jwks_uri``, verify the id token signature.
    4. Enforce ``iss`` == configured issuer and ``aud`` contains our client.
    5. Return the normalized profile.
    """
    if not hmac.compare_digest(state or "", expected_state or ""):
        raise SsoStateError("SSO state mismatch")

    client = http_client or httpx.AsyncClient(timeout=15)
    owns_client = http_client is None
    try:
        token_resp = await client.post(
            provider.token_endpoint,
            data={
                "grant_type": "authorization_code",
                "code": code,
                "redirect_uri": redirect_uri,
                "client_id": provider.client_id,
                "client_secret": provider.client_secret,
            },
            headers={"Accept": "application/json"},
        )
        token_resp.raise_for_status()
        token_payload = token_resp.json()

        id_token = token_payload.get("id_token")
        if not id_token:
            raise SsoVerificationError("OIDC token response missing id_token")

        # Reuse the same client (and any mocked transport) for the JWKS fetch.
        claims = await _verify_id_token(provider, id_token, http_client=client)
    except SsoVerificationError:
        raise
    except Exception as exc:
        raise SsoVerificationError(f"OIDC token exchange failed: {exc}") from exc
    finally:
        if owns_client:
            await client.aclose()

    return SsoProfile(
        protocol="oidc",
        sub=str(claims.get("sub") or ""),
        email=str(claims.get("email") or ""),
        name=str(claims.get("name") or claims.get("preferred_username") or ""),
        groups=[str(g) for g in (claims.get("groups") or []) if isinstance(g, str)],
    )


async def _verify_id_token(
    provider: OidcProviderConfig,
    id_token: str,
    *,
    http_client: httpx.AsyncClient | None = None,
) -> dict[str, Any]:
    """Verify and decode an OIDC id token against the provider JWKS.

    ``python-jose`` provides RS256/ES256/HS256 verification.  The configured
    issuer must match ``iss`` exactly and ``aud`` must contain our
    ``client_id``.  ``http_client`` is used when provided so tests can mock
    the JWKS fetch; otherwise a short-lived client is created.
    """
    from jose import JWTError, jwt
    from jose.jwk import construct

    try:
        unverified = jwt.get_unverified_header(id_token)
    except JWTError as exc:
        raise SsoVerificationError(f"bad OIDC id token header: {exc}") from exc

    alg = str(unverified.get("alg") or "")
    kid = str(unverified.get("kid") or "")

    client = http_client or httpx.AsyncClient(timeout=15)
    owns_client = http_client is None
    try:
        jwks_resp = await client.get(provider.jwks_uri)
        jwks_resp.raise_for_status()
        keyset = jwks_resp.json()
    finally:
        if owns_client:
            await client.aclose()
    raw_keys = keyset.get("keys") if isinstance(keyset, dict) else None
    if not isinstance(raw_keys, list):
        raise SsoVerificationError("OIDC JWKS document has no keys list")
    if kid:
        candidate_keys = [k for k in raw_keys if str(k.get("kid") or "") == kid]
        if not candidate_keys:
            raise SsoVerificationError(f"OIDC JWKS has no key with kid={kid!r}")
    else:
        candidate_keys = raw_keys
    if not candidate_keys:
        raise SsoVerificationError("OIDC JWKS contains no usable key")

    claims: dict[str, Any] | None = None
    last_error: Exception | None = None
    for key in candidate_keys:
        try:
            key_obj = construct(key)
            claims = jwt.decode(
                id_token,
                key_obj,
                algorithms=[alg] if alg else None,
                options={"verify_aud": True},
                audience=provider.client_id,
                issuer=provider.issuer,
            )
            break
        except Exception as exc:  # JWTError and friends
            last_error = exc
            continue
    if claims is None:
        raise SsoVerificationError(
            f"OIDC id token verification failed: {last_error or 'no key matched'}"
        )
    return claims


# ---------------------------------------------------------------------------
# SAML — HTTP-POST binding (SAMLResponse base64 payload)
# ---------------------------------------------------------------------------


def parse_saml_response(raw_saml: str) -> SamlResponseEnvelope:
    """Parse a base64-encoded SAML Response into its parts without verification.

    Use :func:`verify_saml_response` for the security-sensitive path; this
    only extracts the fields needed for verification/error messages.
    """
    from .saml import parse_saml_response as _parse

    return _parse(raw_saml)


async def verify_saml_response(
    provider: SamlProviderConfig,
    raw_saml: str,
    *,
    expected_relay_state: str,
    relay_state: str | None = None,
) -> SsoProfile:
    """Verify a SAML Response (HTTP-POST binding) and return its profile.

    The signature is checked against the IdP certificate, the Audience
    restriction must name our SP, and the RelayState must match what the SP
    issued.
    """
    if not hmac.compare_digest(relay_state or "", expected_relay_state or ""):
        raise SsoStateError("SAML RelayState mismatch")
    from .saml import verify_saml_response as _verify

    return _verify(provider, raw_saml)


# ---------------------------------------------------------------------------
# State nonce helpers (shared by both flows)
# ---------------------------------------------------------------------------


def new_state() -> str:
    """A fresh, unguessable state token stored server-side."""
    return secrets.token_urlsafe(24)


def new_nonce() -> str:
    return secrets.token_urlsafe(16)


# ---------------------------------------------------------------------------
# Account mapping
# ---------------------------------------------------------------------------


def upsert_sso_user(
    profile: SsoProfile,
    *,
    role: str = "user",
    preset: str = "standard",
) -> dict[str, Any]:
    """Map a verified SSO profile to a local account, creating it if needed.

    The local username is derived from the stable SSO key so the same IdP
    subject always resolves to the same account: ``sso-<protocol>-<digest>``.
    This keeps SSO logins independent of the local password store — an SSO
    account has no password and cannot be taken over through a local password
    reset.
    """
    from deeptutor.multi_user.identity import save_user
    from deeptutor.services.auth import list_users

    key = profile.key()
    digest = hashlib.sha256(key.encode("utf-8")).hexdigest()[:16]
    username = f"sso-{digest}"

    existing = next((u for u in list_users() if u.get("username") == username), None)
    if existing is not None:
        return existing

    # ``save_user`` with a random bcrypt hash means the account cannot be
    # logged into via the local password path.
    import bcrypt

    placeholder_hash = bcrypt.hashpw(secrets.token_bytes(24), bcrypt.gensalt()).decode()
    record = save_user(
        username,
        placeholder_hash,
        role=role,  # type: ignore[arg-type]
        preset=preset,  # type: ignore[arg-type]
    )
    logger.info("Created SSO account %s from %s", username, key)
    return record


def sso_session_claims(profile: SsoProfile, account: dict[str, Any]) -> dict[str, Any]:
    """Claims to bake into the normal DeepTutor session token.

    ``create_token`` already embeds ``tenant`` from the request context; SSO
    providers may assert groups that map to tenant membership, which the caller
    can translate before this helper is invoked.
    """
    return {
        "username": str(account.get("username") or ""),
        "role": str(account.get("role") or "user"),
        "user_id": str(account.get("id") or ""),
    }


__all__ = [
    "OidcProviderConfig",
    "SamlProviderConfig",
    "SsoProfile",
    "build_oidc_authorization_url",
    "exchange_oidc_code",
    "new_nonce",
    "new_state",
    "parse_saml_response",
    "sso_session_claims",
    "upsert_sso_user",
    "verify_saml_response",
]
