"use client";

import AssistantResponse from "@/components/common/AssistantResponse";
import { CallTracePanel } from "@/components/chat/home/TracePanels";
import type { StreamEvent } from "@/lib/unified-ws";

const events: StreamEvent[] = [
  {
    type: "stage_start",
    source: "chat",
    stage: "thinking",
    content: "",
    metadata: {
      call_id: "chat-thinking-5a6727fc53",
      phase: "thinking",
      label: "Reasoning",
      call_kind: "llm_reasoning",
      trace_id: "chat-thinking",
      trace_role: "thought",
      trace_group: "stage",
    },
    session_id: "debug",
    turn_id: "debug",
    seq: 2,
    timestamp: 1773336215.742659,
  },
  {
    type: "progress",
    source: "chat",
    stage: "thinking",
    content: "Reasoning",
    metadata: {
      current: 0,
      total: 0,
      call_id: "chat-thinking-5a6727fc53",
      phase: "thinking",
      label: "Reasoning",
      call_kind: "llm_reasoning",
      trace_id: "chat-thinking",
      trace_role: "thought",
      trace_group: "stage",
      trace_kind: "call_status",
      call_state: "running",
    },
    session_id: "debug",
    turn_id: "debug",
    seq: 3,
    timestamp: 1773336215.742673,
  },
  {
    type: "thinking",
    source: "chat",
    stage: "thinking",
    content: "Hello! How can I help you with your studies today? Feel free to share",
    metadata: {
      call_id: "chat-thinking-5a6727fc53",
      phase: "thinking",
      label: "Reasoning",
      call_kind: "llm_reasoning",
      trace_id: "chat-thinking",
      trace_role: "thought",
      trace_group: "stage",
      trace_kind: "llm_chunk",
    },
    session_id: "debug",
    turn_id: "debug",
    seq: 4,
    timestamp: 1773336218.230997,
  },
  {
    type: "thinking",
    source: "chat",
    stage: "thinking",
    content: " a topic you're working on or a specific question you have!",
    metadata: {
      call_id: "chat-thinking-5a6727fc53",
      phase: "thinking",
      label: "Reasoning",
      call_kind: "llm_reasoning",
      trace_id: "chat-thinking",
      trace_role: "thought",
      trace_group: "stage",
      trace_kind: "llm_chunk",
    },
    session_id: "debug",
    turn_id: "debug",
    seq: 5,
    timestamp: 1773336218.258614,
  },
  {
    type: "progress",
    source: "chat",
    stage: "thinking",
    content: "",
    metadata: {
      current: 0,
      total: 0,
      call_id: "chat-thinking-5a6727fc53",
      phase: "thinking",
      label: "Reasoning",
      call_kind: "llm_reasoning",
      trace_id: "chat-thinking",
      trace_role: "thought",
      trace_group: "stage",
      trace_kind: "call_status",
      call_state: "complete",
    },
    session_id: "debug",
    turn_id: "debug",
    seq: 6,
    timestamp: 1773336218.272324,
  },
  {
    type: "stage_end",
    source: "chat",
    stage: "thinking",
    content: "",
    metadata: {
      call_id: "chat-thinking-5a6727fc53",
      phase: "thinking",
      label: "Reasoning",
      call_kind: "llm_reasoning",
      trace_id: "chat-thinking",
      trace_role: "thought",
      trace_group: "stage",
    },
    session_id: "debug",
    turn_id: "debug",
    seq: 7,
    timestamp: 1773336218.2725089,
  },
  {
    type: "stage_start",
    source: "chat",
    stage: "observing",
    content: "",
    metadata: {
      call_id: "chat-observing-8015201f3e",
      phase: "observing",
      label: "Observation",
      call_kind: "llm_observation",
      trace_id: "chat-observing",
      trace_role: "observe",
      trace_group: "stage",
    },
    session_id: "debug",
    turn_id: "debug",
    seq: 11,
    timestamp: 1773336218.2726111,
  },
  {
    type: "progress",
    source: "chat",
    stage: "observing",
    content: "Observation",
    metadata: {
      current: 0,
      total: 0,
      call_id: "chat-observing-8015201f3e",
      phase: "observing",
      label: "Observation",
      call_kind: "llm_observation",
      trace_id: "chat-observing",
      trace_role: "observe",
      trace_group: "stage",
      trace_kind: "call_status",
      call_state: "running",
    },
    session_id: "debug",
    turn_id: "debug",
    seq: 12,
    timestamp: 1773336218.272616,
  },
  {
    type: "observation",
    source: "chat",
    stage: "observing",
    content:
      "**Internal Observation Note:**\n\n*   **Confirmed Facts:** The interaction is in the initial engagement phase. No specific academic topic, question, or problem has been identified yet.\n*   **Key Evidence:** The tutor provided a standard welcoming prompt to elicit a subject or query from the student. No tools were required as there was no data to process.\n*   **Remaining Uncertainty:** The student's specific needs, grade level, and subject area are currently unknown.\n*   **Final Answer Emphasis:** The response should remain focused on encouraging the student to provide a specific topic or question to begin the tutoring session. No factual explanation is possible until the student responds.",
    metadata: {
      call_id: "chat-observing-8015201f3e",
      phase: "observing",
      label: "Observation",
      call_kind: "llm_observation",
      trace_id: "chat-observing",
      trace_role: "observe",
      trace_group: "stage",
      trace_kind: "observation",
    },
    session_id: "debug",
    turn_id: "debug",
    seq: 13,
    timestamp: 1773336221.387284,
  },
  {
    type: "progress",
    source: "chat",
    stage: "observing",
    content: "",
    metadata: {
      current: 0,
      total: 0,
      call_id: "chat-observing-8015201f3e",
      phase: "observing",
      label: "Observation",
      call_kind: "llm_observation",
      trace_id: "chat-observing",
      trace_role: "observe",
      trace_group: "stage",
      trace_kind: "call_status",
      call_state: "complete",
    },
    session_id: "debug",
    turn_id: "debug",
    seq: 18,
    timestamp: 1773336222.169034,
  },
  {
    type: "stage_end",
    source: "chat",
    stage: "observing",
    content: "",
    metadata: {
      call_id: "chat-observing-8015201f3e",
      phase: "observing",
      label: "Observation",
      call_kind: "llm_observation",
      trace_id: "chat-observing",
      trace_role: "observe",
      trace_group: "stage",
    },
    session_id: "debug",
    turn_id: "debug",
    seq: 19,
    timestamp: 1773336222.16907,
  },
  {
    type: "stage_start",
    source: "chat",
    stage: "responding",
    content: "",
    metadata: {
      call_id: "chat-responding-fed2628990",
      phase: "responding",
      label: "Final response",
      call_kind: "llm_final_response",
      trace_id: "chat-responding",
      trace_role: "response",
      trace_group: "stage",
    },
    session_id: "debug",
    turn_id: "debug",
    seq: 20,
    timestamp: 1773336222.1691148,
  },
  {
    type: "progress",
    source: "chat",
    stage: "responding",
    content: "Final response",
    metadata: {
      current: 0,
      total: 0,
      call_id: "chat-responding-fed2628990",
      phase: "responding",
      label: "Final response",
      call_kind: "llm_final_response",
      trace_id: "chat-responding",
      trace_role: "response",
      trace_group: "stage",
      trace_kind: "call_status",
      call_state: "running",
    },
    session_id: "debug",
    turn_id: "debug",
    seq: 21,
    timestamp: 1773336222.16912,
  },
  {
    type: "content",
    source: "chat",
    stage: "responding",
    content:
      "Hello! I'm here to help you with your studies. What subject or specific topic are we working on today? Feel free to share a question or a problem you're stuck on, and we can dive right in!",
    metadata: {
      call_id: "chat-responding-fed2628990",
      phase: "responding",
      label: "Final response",
      call_kind: "llm_final_response",
      trace_id: "chat-responding",
      trace_role: "response",
      trace_group: "stage",
      trace_kind: "llm_chunk",
    },
    session_id: "debug",
    turn_id: "debug",
    seq: 22,
    timestamp: 1773336227.46332,
  },
  {
    type: "progress",
    source: "chat",
    stage: "responding",
    content: "",
    metadata: {
      current: 0,
      total: 0,
      call_id: "chat-responding-fed2628990",
      phase: "responding",
      label: "Final response",
      call_kind: "llm_final_response",
      trace_id: "chat-responding",
      trace_role: "response",
      trace_group: "stage",
      trace_kind: "call_status",
      call_state: "complete",
    },
    session_id: "debug",
    turn_id: "debug",
    seq: 25,
    timestamp: 1773336227.565161,
  },
  {
    type: "stage_end",
    source: "chat",
    stage: "responding",
    content: "",
    metadata: {
      call_id: "chat-responding-fed2628990",
      phase: "responding",
      label: "Final response",
      call_kind: "llm_final_response",
      trace_id: "chat-responding",
      trace_role: "response",
      trace_group: "stage",
    },
    session_id: "debug",
    turn_id: "debug",
    seq: 26,
    timestamp: 1773336227.5652092,
  },
];

const response =
  "Hello! I'm here to help you with your studies. What subject or specific topic are we working on today? Feel free to share a question or a problem you're stuck on, and we can dive right in!";

export default function DebugTracePage() {
  return (
    <main className="min-h-screen bg-[var(--background)] px-8 py-10 text-[var(--foreground)]">
      <div className="mx-auto max-w-[1200px]">
        <CallTracePanel events={events} />
        <AssistantResponse content={response} />
      </div>
    </main>
  );
}
